### ISSUE TITLE
nv installation

### ISSUE THREAD

**Issue by n-shift** [shift-d/nv#1]
## Installation methods
- [X] Shell script
- [X] PowerShell script

---

**Comment by n-shift** [comment]
I've already done `.sh` and `.ps1` installation, and would like to give user an option to install config with nix.
AFAIK the best method for installing configurations for nix - is using [home-manager](https://nix-community.github.io/home-manager/).

**Comment by fufexan** [comment]
Installing using nix would mean the user has an immutable config, which they can update after you update this repo. It may not be what you want though.

**Comment by n-shift** [comment]
You might be right: my goal is to fill `~/.config/nvim/` directory with content of this repository. Plus ensure that git and neovim 0.5.0+ is installed

**Comment by fufexan** [comment]
Filling that directory isn't necessary. You could have nvim pick up config files from the nix store. That way, people can have your `nv` and their own `nvim` config separately and non-conflicting.

**Comment by n-shift** [comment]
Well, my goal - is to provide small, clean, and well-documented glue for your config, I am not sure that having `nv` and `nvim` separated - is what i want

**Comment by n-shift** [comment]
And adding extensibility options as nix flake moves concept of good lua configuration to good nix configuration
